# Generated by Django 4.2.4 on 2023-09-08 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0005_entregable_estudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='cursos',
            field=models.ManyToManyField(to='AppCoder.curso'),
        ),
    ]
