# Generated by Django 4.2.4 on 2023-09-08 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0006_profesor_cursos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ('nombre', '-camada'), 'verbose_name': 'Course', 'verbose_name_plural': 'The Courses'},
        ),
        migrations.AddField(
            model_name='curso',
            name='fecha_creacion',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='curso',
            unique_together={('nombre', 'camada')},
        ),
    ]
