# Generated by Django 4.2.4 on 2023-09-11 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0007_alter_curso_options_curso_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='fecha_creacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
